---
title: "ERP原理与应用"
subtitle: "第一章 初识ERP"
author: "陆海波"
date: "2019/3/5"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css, extra.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(kableExtra)
```


## 财富、制造业和竞争

--
- 财富从哪里来？

--
  - 自然资源、生产制造、服务
  
--
  - 而制造业是创造财富的主要方式，是国民经济的支柱

--
- 由于现代技术特别是交通和通信技术的发展，企业面对的竞争环境越来越复杂，那么一个世界级企业的竞争优势是什么呢？

--
  - 产品、技术
  
--
  - 更深层次的是：.red[管理理念与工具]


---
## 制造业悖论--- 一些难解而又必须解决的问题

--
- 如何满足多变的市场需求？
- 如何准确及时地做出客服承诺？
- 如何处理紧急的客户订单？
- 如何保持均衡的生产计划和活动？
- 如何准确及时地了解生产情况？
- 如何管理供应商？

---
## 制造业悖论--- 一些难解而又必须解决的问题

--
- 如何避免物料短缺？
- 如何避免库存积压？
- 如何提高产品质量？
- 如何降低产品成本？
- 如何及时做好财务分析？真正发挥财务管理的计划、控制和分析的作用？
- 如何使企业的各个职能部门能够以统一的观点和共同的语言来处理问题？

---
## 制造业悖论--- 一些难解而又必须解决的问题

如何消除这些悖论？

--
- 要消除悖论就要消除产生悖论的条件

--
- 这就需要一个以计算机为工具的有效的 .red[计划与控制系统]

--

而ERP就是这样的计划与控制系统
  
---
## 制造业基本方程和MRP 

制造业的基本特点：

- 要制造什么产品？
- 要用什么原材料或零部件来制造这些产品？
- 手中有什么原材料或零部件？
- 还应当再准备什么原材料或零部件？

--

这四个问题构成了制造业的基本方程：

--

.quote[
制造产品数 $\times$ 每件产品所需零件数 - 库存现有零件数 = 尚缺零件数
]

---
## 制造业基本方程和MRP 

MRP (物料需求计划 material requirements planning) 是 ERP 的核心，用来模拟和解决制造业基本方程的

--

MRP 的基本逻辑：

- 依据供需平衡的思想

- 根据主生产计划、物料清单（产品结构文件）和库存记录，对每种物料进行计算，指出何时将会发生物料短缺，并给出建议，以最小库存量满足并避免物料短缺，从而得到 .red[合理的物料需求计划]


---
## 制造业基本方程和MRP 

ERP的发展过程就是一个资源计划与控制的集成范围不断扩大的过程：

- 从物料到能力，到企业所有的资源，到面向供应链的资源，集成的范围不断扩大
- 但其核心仍然是MRP，而供需平衡的思想也体现在集成的范围不断扩大的每个层面上

--

在制造业中应用计算机技术来提高企业的管理水平，其核心问题就是求解制造业基本方程

--

.quote[
ERP正是计算机技术和制造业基本方程相结合的产物
]



---
## ERP 能够做什么

--
- 能解决既有物料短缺又有库存积压的库存管理难题

--
- 能解决多变的市场与均衡生产之间的矛盾

--
- 使得对客户的供货承诺做得更好

--
- 可以提高质量并降低成本

--
- 可以改变企业中的部门本位观


---
## 成功实施ERP的关键因素

--
- 数据

--
- 技术

--
- 人

